### ISSUE TITLE
Dependencies are outdated

### ISSUE THREAD

**Issue by wilson-ko** [robotology/tactile-control#2]
I tried building this from source. I installed the latest yarp (2.30.70), but it seems like that the code from this repository expects a version from older than 2.30.65. The reason I suspect this is because I get the following error when trying to compile:

ControllersUtil.h:33:28: error: ‘IOpenLoopControl’ in namespace ‘yarp::dev’ does not name a type yarp::dev::IOpenLoopControl *iOLC;

It seem like IOpenLoopControl has been deprecated since yarp 2.30.65. I tried to fix this myself, but as I am not familiar with yarp, I do not know what I should replace IOpenLoopControl with. Could you guys please have a look at this? Thanks.

**Comment by pattacini** [comment]
Thanks @wilson-ko for spotting this out

@massimoregoli could you please look into this?

**Comment by massimoregoli** [comment]
Hi @wilson-ko , sorry that module has outdated dependencies because it is meant to be changed in order to make use of the tactile-control libraries that you can find in the same repository (`tactile-control-lib`). Since it is not just a matter of changing a few lines of code, I will temporary remove it from the repository to avoid further compilation issues. If you want examples of modules using the tactile-control libraries, have a look at `tactile-control-wrapper` (still in the same repository) or at the superquadric grasp module at the following link:

https://github.com/robotology/superquadric-grasp

**Comment by wilson-ko** [comment]
@massimoregoli I see, thanks for your comment. I found out from your colleague that I don't need this package for my purposes (I was interested in using superquadric grasping). So in the end it worked out for me without compiling this package. Thanks for looking at this though!
